POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwNzY4MDR9.ywtlUXBblEqdW0M--BRUBEbn5lXq_6VvFskr16DWpx4
Content-Type: application/json

{
  "product_id": 3,
  "quantity": 4
}

###

GET http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwNzY4MDR9.ywtlUXBblEqdW0M--BRUBEbn5lXq_6VvFskr16DWpx4

###
DELETE http://localhost:3000/carted_products/2.json