POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MTU3NTF9.jkuCM3BN8sUByE4Bcx2L4tCM2p12cDahsHHyrLm1se8
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 1,
  "subtotal": 9,
  "tax": 9,
  "total": 6
}

###

GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MTU3NTF9.jkuCM3BN8sUByE4Bcx2L4tCM2p12cDahsHHyrLm1se8
Content-Type: application/json

###

GET http://localhost:3000/orders/1.json