GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwNzY1OTV9.YEctyeevtsSUgtnRW1PvE1YfMIkCE-xUAeO-giBKUko
Content-Type: application/json

###
GET http://localhost:3000/products/3.json