POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "bob",
  "email": "bob@fakeyfakefake.com",
  "password": "aluminum",
  "password_confirmation": "aluminum"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bob@fakeyfakefake.com",
  "password": "aluminum"
}

# JWT: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkxNTc2MzV9.QBmWfCYtUCwUvF5MzG1FEUHRRv-k1WdaoTNz6nmhfRo