POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Mike",
  "email": "mike@fakeyfakefake.com",
  "password": "aluminum",
  "password_confirmation": "aluminum"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mike@fakeyfakefake.com",
  "password": "aluminum"
}